#!/usr/bin/php
<?php

require __DIR__ . '/vendor/autoload.php';

use ChannelEngine\Console\Commands\ChannelEngineBuildCommand;
use Symfony\Component\Console\Application;

$application = new Application();

// register commands
$application->add( new ChannelEngineBuildCommand() );

$application->run();